# config/meta.yml

meta_product_name: "Walking Stick"
meta_title: "Walking Stick - Walking Tours Reimaged!"
meta_description: "Free Walking Tours Meets Podcasts!"
meta_image: "walking_stick_logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
